// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `FileTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

/**
 * 思路:
 * 1 客户端 通知服务器  需要上传 保存的文件的路径,文件名 ,文件大小,服务器成功创建此文件大小空间,则返回标识码
 * 2 服务端 开始接受文件
 * 使用 RandomAccessFile ,并保存对象
 * 绑定唯一标识 TAG - RandomAccessFile对象, 存入Map
 * 3 客户端 使用标识与 服务端进行数据传输
 **/
public interface _IFileUploadServiceOperationsNC
{
    /**
     * 请求上传文件
     **/
    String request(FileUploadInfo fui);

    /**
     * 上传文件数据片段
     * tag 文件远程标识
     * start 起点
     * bytes 字节数据
     **/
    void transfer(String tag, long start, byte[] bytes);

    /**
     * 上传完成
     **/
    void complete(String tag);
}
