// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `DataTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

/**
 * 请求上传文件
 **/

public abstract class Callback_IDataTransferService_request
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<bottle.transfer.dts.FileUploadRespond>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IDataTransferServicePrxHelper.__request_completed(this, __result);
    }
}
