// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `DataTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

/**
 * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
 * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
 **/

public abstract class Callback_IDataTransferService_requestFileUpload
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<bottle.transfer.dts.TransferSequence[]>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        IDataTransferServicePrxHelper.__requestFileUpload_completed(this, __result);
    }
}
