// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `DataTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

public class FileUploadRequest implements java.lang.Cloneable, java.io.Serializable
{
    public String filePath;

    public String fileName;

    public long fileSize;

    public FileUploadRequest()
    {
        filePath = "";
        fileName = "";
    }

    public FileUploadRequest(String filePath, String fileName, long fileSize)
    {
        this.filePath = filePath;
        this.fileName = fileName;
        this.fileSize = fileSize;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FileUploadRequest _r = null;
        if(rhs instanceof FileUploadRequest)
        {
            _r = (FileUploadRequest)rhs;
        }

        if(_r != null)
        {
            if(filePath != _r.filePath)
            {
                if(filePath == null || _r.filePath == null || !filePath.equals(_r.filePath))
                {
                    return false;
                }
            }
            if(fileName != _r.fileName)
            {
                if(fileName == null || _r.fileName == null || !fileName.equals(_r.fileName))
                {
                    return false;
                }
            }
            if(fileSize != _r.fileSize)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::dts::FileUploadRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, filePath);
        __h = IceInternal.HashUtil.hashAdd(__h, fileName);
        __h = IceInternal.HashUtil.hashAdd(__h, fileSize);
        return __h;
    }

    public FileUploadRequest
    clone()
    {
        FileUploadRequest c = null;
        try
        {
            c = (FileUploadRequest)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(filePath);
        __os.writeString(fileName);
        __os.writeLong(fileSize);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        filePath = __is.readString();
        fileName = __is.readString();
        fileSize = __is.readLong();
    }

    static public void
    __write(IceInternal.BasicStream __os, FileUploadRequest __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FileUploadRequest
    __read(IceInternal.BasicStream __is, FileUploadRequest __v)
    {
        if(__v == null)
        {
             __v = new FileUploadRequest();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FileUploadRequest __nullMarshalValue = new FileUploadRequest();

    public static final long serialVersionUID = -360873070L;
}
