// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `DataTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

/**
 * 文件上传请求
 **/
public class FileUploadRequest implements java.lang.Cloneable, java.io.Serializable
{
    public String path;

    public String name;

    public long size;

    public FileUploadRequest()
    {
        path = "";
        name = "";
    }

    public FileUploadRequest(String path, String name, long size)
    {
        this.path = path;
        this.name = name;
        this.size = size;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FileUploadRequest _r = null;
        if(rhs instanceof FileUploadRequest)
        {
            _r = (FileUploadRequest)rhs;
        }

        if(_r != null)
        {
            if(path != _r.path)
            {
                if(path == null || _r.path == null || !path.equals(_r.path))
                {
                    return false;
                }
            }
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(size != _r.size)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::dts::FileUploadRequest");
        __h = IceInternal.HashUtil.hashAdd(__h, path);
        __h = IceInternal.HashUtil.hashAdd(__h, name);
        __h = IceInternal.HashUtil.hashAdd(__h, size);
        return __h;
    }

    public FileUploadRequest
    clone()
    {
        FileUploadRequest c = null;
        try
        {
            c = (FileUploadRequest)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(path);
        __os.writeString(name);
        __os.writeLong(size);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        path = __is.readString();
        name = __is.readString();
        size = __is.readLong();
    }

    static public void
    __write(IceInternal.BasicStream __os, FileUploadRequest __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FileUploadRequest
    __read(IceInternal.BasicStream __is, FileUploadRequest __v)
    {
        if(__v == null)
        {
             __v = new FileUploadRequest();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FileUploadRequest __nullMarshalValue = new FileUploadRequest();

    public static final long serialVersionUID = 1422373748L;
}
