// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `DataTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

/**
 * 思路:
 * 1 客户端 请求服务器  -  保存的文件路径, 保存的文件名 ,文件大小
 * 2 服务端 开辟文件空间 如果不够 则返回失败
 * 使用 RandomAccessFile ,并保存对象
 * 绑定唯一标识 TAG - RandomAccessFile对象- 存入Map等数据结构
 * 返回一个 包含唯一标识 TAG的分片对象(list) - 对象包含: 文件数据片段起点,大小,数据片段Tag,数据Byte(空)
 * 3 客户端获取 分片对象List ,单线程上传 - 循环list 填充数据,使用RandomAccessFile  (多线程上传- 线程池+片段数据上传即可)
 * 4 客户端调用文件传送成功结构- 服务端关闭Raf (服务端存在间隔监听线程,定时检测关闭Raf,避免资源占用未释放)
 **/
public interface IDataTransferServicePrx extends Ice.ObjectPrx
{
    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     **/
    public TransferSequence[] requestFileUpload(FileUploadRequest request);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     **/
    public TransferSequence[] requestFileUpload(FileUploadRequest request, java.util.Map<String, String> __ctx);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, java.util.Map<String, String> __ctx);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, Ice.Callback __cb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, Callback_IDataTransferService_requestFileUpload __cb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, java.util.Map<String, String> __ctx, Callback_IDataTransferService_requestFileUpload __cb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, 
                                                   IceInternal.Functional_GenericCallback1<TransferSequence[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, 
                                                   IceInternal.Functional_GenericCallback1<TransferSequence[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<TransferSequence[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_requestFileUpload(FileUploadRequest request, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<TransferSequence[]> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 请求文件上传,获取文件上传标识,文件片段序列,失败返回空序列
     * 文件路径(null则默认),文件名(null则默认),文件大小(必须大于0)
     * @param __result The asynchronous result object.
     **/
    public TransferSequence[] end_requestFileUpload(Ice.AsyncResult __result);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     **/
    public int uploadSequence(TransferSequence ts);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     **/
    public int uploadSequence(TransferSequence ts, java.util.Map<String, String> __ctx);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, java.util.Map<String, String> __ctx);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, Ice.Callback __cb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, Callback_IDataTransferService_uploadSequence __cb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, java.util.Map<String, String> __ctx, Callback_IDataTransferService_uploadSequence __cb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadSequence(TransferSequence ts, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_IntCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 上传已经填充的文件数据片段 成功返回0 ,失败返回-1
     * @param __result The asynchronous result object.
     **/
    public int end_uploadSequence(Ice.AsyncResult __result);

    /**
     * 上传完成
     **/
    public void uploadComplete(long tag);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     **/
    public void uploadComplete(long tag, java.util.Map<String, String> __ctx);

    /**
     * 上传完成
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, java.util.Map<String, String> __ctx);

    /**
     * 上传完成
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, Ice.Callback __cb);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 上传完成
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, Callback_IDataTransferService_uploadComplete __cb);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, java.util.Map<String, String> __ctx, Callback_IDataTransferService_uploadComplete __cb);

    /**
     * 上传完成
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 上传完成
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 上传完成
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_uploadComplete(long tag, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_VoidCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 上传完成
     * @param __result The asynchronous result object.
     **/
    public void end_uploadComplete(Ice.AsyncResult __result);
}
