// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `FileTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

public final class IFileUploadServiceHolder extends Ice.ObjectHolderBase<IFileUploadService>
{
    public
    IFileUploadServiceHolder()
    {
    }

    public
    IFileUploadServiceHolder(IFileUploadService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof IFileUploadService)
        {
            value = (IFileUploadService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _IFileUploadServiceDisp.ice_staticId();
    }
}
