// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `FileTransferService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package bottle.transfer.dts;

public final class TransferSequenceHolder extends Ice.Holder<TransferSequence>
{
    public
    TransferSequenceHolder()
    {
    }

    public
    TransferSequenceHolder(TransferSequence value)
    {
        super(value);
    }
}
